apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: github-event-gw
  name: github-event-gw
  namespace: kyma-integration
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: github-event-gw
  type: ClusterIP
status:
  loadBalancer: {}
