docs:
  - template:
      displayName: "github-connector-0.1.0"
      description: "Github Connector documentation"
      sources:
        - type: markdown
          name: docs
          mode: package
          filter: (docs/(.*?)\.(md|svg)$)
